name: youtube3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  fab_circular_menu: ^1.0.2
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0

dev_dependencies:

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
